// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_llama from "./routes/api/llama.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $workersAi_llama from "./routes/workersAi/llama.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Llama from "./islands/Llama.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/llama.ts": $api_llama,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/workersAi/llama.tsx": $workersAi_llama,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Llama.tsx": $Llama,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
